{"name": "Переход на страницу восстановления пароля", "status": "broken", "statusDetails": {"message": "TypeError: 'str' object is not callable", "trace": "self = <tests.test_recovery.TestRecoveryPassword object at 0x0000027E347AE150>\nlogin_page = <pages.login_page.LoginPage object at 0x0000027E34872B10>\nrecovery_page = <pages.recovery_page.RecoveryPage object at 0x0000027E34872B70>\n\n    @allure.title(\"Переход на страницу восстановления пароля\")\n    def test_go_to_recovery_password_page(self, login_page, recovery_page):\n>       login_page.open()  # открываем страницу логина\n\ntests\\test_recovery.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x0000027E34872B10>, url = None\n\n    def open(self, url: str = None):\n        \"\"\"Открытие страницы. Если url не указан — используется path().\"\"\"\n>       self._url = url if url else self.path()\nE       TypeError: 'str' object is not callable\n\npages\\base_page.py:45: TypeError"}, "start": 1749737409480, "stop": 1749737409480, "uuid": "030bf686-46e0-467c-86da-e4a453d7139e", "historyId": "4ad9ec9d043d8121c92a631decb69449", "testCaseId": "4ad9ec9d043d8121c92a631decb69449", "fullName": "tests.test_recovery.TestRecoveryPassword#test_go_to_recovery_password_page", "labels": [{"name": "feature", "value": "Восстановление пароля"}, {"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_recovery"}, {"name": "subSuite", "value": "TestRecoveryPassword"}, {"name": "host", "value": "DESKTOP-05J7DPF"}, {"name": "thread", "value": "22940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_recovery"}]}